const ITEM_LIST = [
    // ======추천레시피=====================================================
    [
        {item_no: 1, src: '추천/item1.jpg', title:'방울토마토 매실절임',sub_title:'달콤상큼함이 퍼져요',level:'쉬움',time:'20분',coment:'방울토마토를 깨무는 순간, 매실향이 입안 가득 퍼지는 즐거움! 여름 별미로 시원하게 즐기기 좋은 ‘방울토마토 매실절임’을 소개해요. 매실은 식중독을 예방해 여름에 먹어주면 좋은 과일인데요~ 매실절임으로 만들어 안주, 간식 등으로 색다르게 즐겨보세요.',
            ingredient:[
                {name:'방울토마토',count:'50개',cost:'3900원'},
                {name:'레몬',count:'1/2개',cost:'2900원'},
                {name:'매실청',count:'2컵',cost:'1900원'},
                {name:'타임(또는 로즈메리)',count:'약간',cost:'2900원'},
            ]
        },
        {item_no: 2, src: 'main/item2.jpg', title:'부대볶음',sub_title:'LG 인덕션 레시피',level:'쉬움',time:'20분',coment:'국물 없이 소시지, 햄 등 각종 재료와 소스를 볶아낸 부대볶음! 국물 없이 즐기는 부대찌개의 맛이라고나 할까요? 소시지와 햄의 풍미를 더욱 진하게 느낄 수 있어 매력적이에요. 만드는 과정도 초간단하답니다! 반찬은 물론 안주로도 강력 추천해요.',
            ingredient:[
                {name:'통조림햄',count:'1/2통(100g)',cost:'3900원'},
                {name:'소시지',count:'2개(85g)',cost:'2900원'},
                {name:'양배추',count:'1/8개(80g)',cost:'1900원'},
                {name:'양파',count:'1/4개',cost:'2900원'},
                {name:'베이크드빈스(생략 가능)',count:'2큰술',cost:'3900원'},
                {name:'대파',count:'1/3개',cost:'4900원'},
                {name:'식용유',count:'3큰술',cost:'6900원'},
                {name:'슬라이스 치즈',count:'1장',cost:'5900원'},
                {name:'통깨',count:'약간',cost:'4900원'}
            ]
        },
        {item_no: 3, src: 'main/item3.jpg', title:'짬뽕',sub_title:'얼큰한 국물',level:'쉬움',time:'30분',coment:'날씨가 쌀쌀해지기 시작하면 뜨끈하고 얼큰한 국물 생각이 절로 나죠. 해물이 듬뿍 들어가 시원하고 깊은 맛이 나는 짬뽕 레시피 소개할게요. 집에서 불맛 내는 꿀팁까지 포함돼 있으니 꼭 한번 따라해 보세요! 매콤한 짬뽕 한 그릇을 다 먹고 나서 고소한 우유 한 잔으로 속을 달래 줘도 좋답니다!',
            ingredient:[
                {name:'오징어',count:'1/2마리',cost:'3900원'},
                {name:'알새우',count:'6~8마리',cost:'2900원'},
                {name:'바지락',count:'한 줌(120g)',cost:'1900원'},
                {name:'돼지고기',count:'60g',cost:'2900원'},
                {name:'양파',count:'1/2개',cost:'3900원'},
                {name:'대파',count:'1대',cost:'4900원'},
                {name:'청경채',count:'3개',cost:'6900원'},
                {name:'배추',count:'2장',cost:'5900원'},
                {name:'목이버섯',count:'2개',cost:'4900원'},
                {name:'표고버섯',count:'2~3개',cost:'3900원'},
                {name:'홍고추',count:'1개',cost:'2900원'},
                {name:'당근',count:'약간',cost:'1900원'},
                {name:'호박',count:'약간',cost:'2900원'},
                {name:'다진 마늘',count:'1작은술',cost:'3900원'},
                {name:'다진 생강',count:'1/2작은술',cost:'4900원'},
                {name:'치킨파우더',count:'1작은술',cost:'6900원'},
                {name:'생중화면',count:'2인분',cost:'5900원'}
            ]
        },
    ],
    // ======best10========================================
    [
        {item_no: 1, src: '1.jpg', title:'참깨 메밀 소바',txt: '뻔한 메밀국수는 안녕! 메밀국수를 조금 더 특별하고 맛있게 먹을 방법을 소개해 드릴게요.'},
        {item_no: 2, src: '2.jpg', title:'야끼소바', txt: '소스 재료가 아주 간단해 누구나 어렵지 않게 만들 수 있어요. 시원한 맥주 한 잔과 야끼소바 어떠세요?'},
        {item_no: 3, src: '3.jpg', title:'쇠고기덮밥', txt: '입에 착 감기는 한 그릇, 가쓰오부시 양념과 쇠고기가 맛있게 어울리는 덮밥.'},
        {item_no: 4, src: '4.jpg', title:'루꼴라 오픈 토스트', txt: '잘 구운 호밀빵 위에 햄과 슬라이스 치즈, 양파 피클과 함께 루꼴라를 듬뿍 올린 오픈 토스트!'},
        {item_no: 5, src: '5.jpg', title:'바지락크림파스타', txt: '바지락이 들어간 요리는 맛이 깊고 담백합니다.'},
        {item_no: 6, src: '6.jpg', title:'베이컨 치즈 말이밥', txt: '한입에 쏙 들어가는 귀여운 비주얼의 베이컨 치즈 말이 밥!'},
        {item_no: 7, src: '7.jpg', title:'대패삼겹 튀김 샐러드', txt: '이색적인 대패삼겹 튀김 샐러드 맛에 빠져 보세요!'},
        {item_no: 8, src: '8.jpg', title:'목살김치찜', txt: '한국인의 영원한 소울푸드, 김치찜 싫어하는 분들은 없을 거예요.'},
        {item_no: 9, src: '9.jpg', title:'로메인 시저샐러드', txt: '로메인 상추와 베이컨 등에 엔초비가 들어간 드레싱을 버무려 먹는 미국식 샐러드.'},
        {item_no: 10, src: '10.jpg', title:'감자뇨끼파스타', txt: '이탈리아의 대표적인 가정식 뇨끼!'}
    ],
    // =====our recipie====================================
    [   
        // 모든요리
        [
            
        ],
        // 메인요리
        [
            {item_no: 1, src: 'main/item1.jpg', title:'돼지맥적구이',sub_title:'부드러운 미국산 목살로 만든',level:'쉬움',time:'35분',coment:'된장 양념에 돼지고기를 재운 뒤 구워낸 돼지맥적구이는 고구려에서 유래된 전통 요리인데요. 특히 이번 요리에서는 담백한 살결과 풍부한 육즙을 가진 미국산 돼지고기 목살을 사용했어요. 부드러운 육질과 깊고 진한 풍미가 된장 양념과 절묘하게 어울린답니다! 목살 사이사이에 된장 양념이 쏙 배어 더욱 부드러운 식감을 느낄 수 있고 구수한 감칠맛이 입안을 맴돌아요. 부추무침과 함께 먹으면 영양과 맛이 더욱 UP! 근사한 한끼로도 아주 좋고, 홈파티 메뉴로도 손색없답니다.',
                ingredient:[
                    {name:'돼지고기 목살',count:'3쪽(500g)',cost:'3900원'},
                    {name:'영양 부추',count:'한 줌',cost:'2900원'},
                    {name:'팽이버섯',count:'1/4봉',cost:'1900원'},
                    {name:'양파',count:'1/4개',cost:'2900원'},
                    {name:'통깨',count:'약간',cost:'3900원'},
                    {name:'식용유',count:'약간',cost:'4900원'},
                    {name:'된장',count:'1+1/2큰술',cost:'6900원'},
                    {name:'간장',count:'1큰술',cost:'5900원'},
                    {name:'올리고당',count:'2큰술',cost:'4900원'},
                    {name:'맛술',count:'2큰술',cost:'3900원'},
                    {name:'설탕',count:'1/2큰술',cost:'2900원'},
                    {name:'다진마늘',count:'1큰술',cost:'1900원'},
                    {name:'생강가루',count:'한 꼬집',cost:'2900원'},
                    {name:'후춧가루',count:'약간',cost:'3900원'}
                ]
            },
            {item_no: 2, src: 'main/item2.jpg', title:'부대볶음',sub_title:'LG 인덕션 레시피',level:'쉬움',time:'20분',coment:'국물 없이 소시지, 햄 등 각종 재료와 소스를 볶아낸 부대볶음! 국물 없이 즐기는 부대찌개의 맛이라고나 할까요? 소시지와 햄의 풍미를 더욱 진하게 느낄 수 있어 매력적이에요. 만드는 과정도 초간단하답니다! 반찬은 물론 안주로도 강력 추천해요.',
                ingredient:[
                    {name:'통조림햄',count:'1/2통(100g)',cost:'3900원'},
                    {name:'소시지',count:'2개(85g)',cost:'2900원'},
                    {name:'양배추',count:'1/8개(80g)',cost:'1900원'},
                    {name:'양파',count:'1/4개',cost:'2900원'},
                    {name:'베이크드빈스(생략 가능)',count:'2큰술',cost:'3900원'},
                    {name:'대파',count:'1/3개',cost:'4900원'},
                    {name:'식용유',count:'3큰술',cost:'6900원'},
                    {name:'슬라이스 치즈',count:'1장',cost:'5900원'},
                    {name:'통깨',count:'약간',cost:'4900원'}
                ]
            },
            {item_no: 3, src: 'main/item3.jpg', title:'짬뽕',sub_title:'얼큰한 국물',level:'쉬움',time:'30분',coment:'날씨가 쌀쌀해지기 시작하면 뜨끈하고 얼큰한 국물 생각이 절로 나죠. 해물이 듬뿍 들어가 시원하고 깊은 맛이 나는 짬뽕 레시피 소개할게요. 집에서 불맛 내는 꿀팁까지 포함돼 있으니 꼭 한번 따라해 보세요! 매콤한 짬뽕 한 그릇을 다 먹고 나서 고소한 우유 한 잔으로 속을 달래 줘도 좋답니다!',
                ingredient:[
                    {name:'오징어',count:'1/2마리',cost:'3900원'},
                    {name:'알새우',count:'6~8마리',cost:'2900원'},
                    {name:'바지락',count:'한 줌(120g)',cost:'1900원'},
                    {name:'돼지고기',count:'60g',cost:'2900원'},
                    {name:'양파',count:'1/2개',cost:'3900원'},
                    {name:'대파',count:'1대',cost:'4900원'},
                    {name:'청경채',count:'3개',cost:'6900원'},
                    {name:'배추',count:'2장',cost:'5900원'},
                    {name:'목이버섯',count:'2개',cost:'4900원'},
                    {name:'표고버섯',count:'2~3개',cost:'3900원'},
                    {name:'홍고추',count:'1개',cost:'2900원'},
                    {name:'당근',count:'약간',cost:'1900원'},
                    {name:'호박',count:'약간',cost:'2900원'},
                    {name:'다진 마늘',count:'1작은술',cost:'3900원'},
                    {name:'다진 생강',count:'1/2작은술',cost:'4900원'},
                    {name:'치킨파우더',count:'1작은술',cost:'6900원'},
                    {name:'생중화면',count:'2인분',cost:'5900원'}
                ]
            },
            {item_no: 4, src: 'main/item4.jpg', title:'스테이크 솥밥',sub_title:'근사한 비주얼의',level:'쉬움',time:'25분',coment:'노릇하게 구운 스테이크를 듬뿍 올린 솥밥! 채끝살과 마늘을 노릇하게 구운 후 남은 오일에 쌀을 볶아 풍미가 기가 막히답니다. LG 인덕션을 이용하면 미세한 열 조절이 가능해 솥밥 실패할 일이 없어요. 근사한 비주얼의 스테이크 솥밥 꼭 한번 만들어 보세요!',
                ingredient:[
                    {name:'채끝살',count:'300g',cost:'3900원'},
                    {name:'쌀',count:'2컵',cost:'2900원'},
                    {name:'쯔유',count:'3큰술',cost:'1900원'},
                    {name:'올리브오일',count:'4큰술',cost:'2900원'},
                    {name:'다시마',count:'1장',cost:'3900원'},
                    {name:'올리브오일',count:'1큰술',cost:'4900원'},
                    {name:'소금',count:'1작은술',cost:'6900원'},
                    {name:'후춧가루',count:'약간',cost:'5900원'},
                    {name:'달걀 노른자',count:'1개',cost:'4900원'},
                    {name:'통마늘',count:'10개',cost:'3900원'},
                    {name:'쪽파',count:'4대',cost:'2900원'},
                    {name:'통깨',count:'약간',cost:'1900원'},
                ]
            },
            {item_no: 5, src: 'main/item5.jpg', title:'대패삼겹 튀김 샐러드',sub_title:'LG 인덕션 레시피',level:'보통',time:'30분',coment:'대패삼겹살은 얇은 두께 덕분에 야들야들한 식감이 매력적인데요. 대패삼겹살을 튀겨내면 바삭바삭하면서도 야들한 식감 속에 고소함을 한껏 머금고 있어 풍미가 훨씬 좋아진답니다! 신선한 채소와 함께 샐러드로 만들면 맛은 물론 영양까지 균형잡힌 식사를 할 수 있어요. 이색적인 대패삼겹 튀김 샐러드 맛에 빠져 보세요! 맥주와 찰떡 궁합을 이뤄 안주로 아주 좋답니다!',
                ingredient:[
                    {name:'대패삼겹살',count:'6줄(100g)',cost:'3900원'},
                    {name:'식용유',count:'2컵',cost:'2900원'},
                    {name:'샐러드 믹스',count:'100g',cost:'1900원'},
                    {name:'소금',count:'2꼬집',cost:'2900원'},
                    {name:'후춧가루',count:'약간',cost:'3900원'},
                    {name:'밀가루',count:'1/2컵',cost:'4900원'},
                    {name:'간장',count:'1큰술',cost:'6900원'},
                    {name:'설탕',count:'1/2큰술',cost:'5900원'},
                    {name:'레몬즙',count:'1큰술',cost:'4900원'},
                    {name:'다진 마늘',count:'1작은술',cost:'3900원'},
                    {name:'다진 파슬리',count:'약간',cost:'2900원'},
                ]  
            },
            {item_no: 6, src: 'main/item6.jpg', title:'빨간 잡채',sub_title:'스트레스 풀리는 맛',level:'쉬움',time:'15분',coment:'쫄깃쫄깃한 당면을 각종 채소와 함께 양념에 볶아 내면 매콤한 맛이 일품인 빨간 잡채가 완성되는데요. 특히 콩나물의 아삭한 식감과 쫄깃한 당면의 식감이 환상적으로 어우러진답니다. 살짝 맵다 싶을 땐 우유를 함께 마시면 좋을 거예요. 빨간 잡채 먹고 스트레스 확 날려 버리세요~!',
                ingredient:[
                    {name:'건당면',count:'150g',cost:'3900원'},
                    {name:'양파',count:'1/2개',cost:'2900원'},
                    {name:'대파',count:'1/2대',cost:'1900원'},
                    {name:'어묵',count:'1장',cost:'3900원'},
                    {name:'콩나물',count:'한 줌(200g)',cost:'4900원'},
                    {name:'식용유',count:'2큰술',cost:'4900원'},
                    {name:'다진 마늘',count:'1작은술',cost:'6900원'},
                    {name:'청양고추',count:'2개',cost:'5900원'},
                    {name:'고추장',count:'1큰술',cost:'4900원'},
                    {name:'고춧가루',count:'3큰술',cost:'3900원'},
                    {name:'굴소스',count:'1/2큰술',cost:'2900원'},
                ]  
            },
            {item_no: 7, src: 'main/item7.jpg', title:'주꾸미 솥밥',sub_title:'LG 인덕션 레시피',level:'보통',time:'30분',coment:'오늘은 새로운 솥밥 레시피를 들고 왔어요. 매콤한 맛이 입맛을 돋우는 주꾸미볶음을 아삭아삭한 미나리와 함께 밥 위에 올리면 뚝딱 완성되는 주꾸미 솥밥! 황금 비율의 양념 덕분에 감칠맛이 폭발한답니다. 색다른 솥밥 레시피에 도전해 보세요!',
                ingredient:[
                    {name:'주꾸미',count:'300g',cost:'3900원'},
                    {name:'쌀',count:'2컵',cost:'2900원'},
                    {name:'미나리',count:'2컵',cost:'1900원'},
                    {name:'통깨',count:'반 줌(80g)',cost:'3900원'},
                    {name:'참기름',count:'1작은술',cost:'4900원'},
                    {name:'식용유',count:'1큰술',cost:'4900원'},
                    {name:'고추장',count:'1+1/2큰술',cost:'6900원'},
                    {name:'고춧가루',count:'1+1/2큰술',cost:'5900원'},
                ]  
            },
            {item_no: 8, src: 'main/item8.jpg', title:'항정살 데리야끼 구이',sub_title:'달콤한 간장소스와 함께 구워낸',level:'쉬움',time:'25분',coment:'살코기 사이사이 마블링이 촘촘히 박혀 있어 쫄깃하면서도 부드러운 식감과 고소하면서도 담백한 맛을 가진 항정살! 돼지 한 마리에서 약 200g 정도밖에 나오지 않는 부위라 더 특별하게 느껴진답니다. 달콤한 간장소스와 함께 구워내 더 풍부한 풍미를 느껴 보세요!',
                ingredient:[
                    {name:'항정살',count:'300g',cost:'3900원'},
                    {name:'대파 흰 부분',count:'1대',cost:'2900원'},
                    {name:'마늘',count:'5개',cost:'1900원'},
                    {name:'생강',count:'1톨',cost:'3900원'},
                    {name:'양파',count:'1/2개',cost:'4900원'},
                    {name:'영양부추(생략 가능)',count:'약간',cost:'4900원'},
                    {name:'간장',count:'2큰술',cost:'6900원'},
                    {name:'맛술',count:'2큰술',cost:'5900원'},
                    {name:'설탕',count:'1/2큰술',cost:'4900원'},
                    {name:'청주',count:'2큰술',cost:'3900원'},
                    {name:'후춧가루',count:'약간',cost:'2900원'},
                ]  
            },
        ],
        // 간단요리
        [
            {item_no: 1, src: 'simple/item1.jpg', title:'단호박 주스',sub_title:'노란빛 행복 한 잔',level:'쉬움',time:'25분',coment:'비타민A와 식이섬유가 풍부한 단호박과 고소하고 깔끔한 맛의 국산 우유를 함께 갈면 보기만 해도 기분 좋아지는 노란빛의 단호박 주스가 탄생해요. 부드럽고 달콤한 맛이 행복을 선사해 줄 거예요. 간편하고 쉽게 만들 수 있는데다 영양이 풍부해 아침 대용으로도 좋답니다!',
                ingredient:[
                    {name:'미니 단호박',count:'1개',cost:'3900원'},
                    {name:'우유',count:'2컵(400ml)',cost:'2900원'},
                    {name:'꿀',count:'1/2큰술',cost:'1900원'},
                ]  
            },
            {item_no: 2, src: 'simple/item2.jpg', title:'요거트 컵',sub_title:'기분 좋은 디저트',level:'쉬움',time:'20분',coment:'보기만 해도 기분이 좋아지는 요거트 컵! 재료들을 그냥 섞는 게 아니라 순서대로 넣고 쌓아 남다른 비주얼을 자랑한답니다. 아침 대용으로 먹기도 좋고요. 비주얼이 워낙 예뻐서 홈파티 디저트로 내놓으면 모든 손님이 좋아할 거예요! 어여쁘고 맛있는 디저트로 기분 전환해 보세요!',
                ingredient:[
                    {name:'요거트',count:'1컵',cost:'3900원'},
                    {name:'그래놀라',count:'4큰술',cost:'2900원'},
                    {name:'블루베리',count:'1컵',cost:'1900원'},
                    {name:'꿀',count:'1큰술',cost:'3900원'},
                    {name:'다진 피칸',count:'10알',cost:'4900원'},
                    {name:'치아씨드',count:'약간',cost:'4900원'},
                ] 
            },
            {item_no: 3, src: 'simple/item3.jpg', title:'썸머 스무디',sub_title:'아침 2분컷 요리',level:'쉬움',time:'02분',coment:'단 1~2분 안에 만들 수 있는데다 속까지 든든하게 채워주는 썸머 스무디! 두부를 넣어 단백질 보충에 탁월하고, 포만감이 높답니다. 귀리우유의 고소함과 바나나&청귤청의 달콤함, 두부의 담백함이 찰떡처럼 어울려요. 블렌더에 넣고 곱게 간 후 그래놀라만 살짝 올려 주면 비주얼까지 어여쁘답니다.',
                ingredient:[
                    {name:'두부',count:'1/4모',cost:'3900원'},
                    {name:'청귤청(혹은 유자청)',count:'30g',cost:'2900원'},
                    {name:'귀리우유',count:'200ml',cost:'1900원'},
                    {name:'그래놀라(카카오)',count:'적당량',cost:'3900원'},
                ] 
            },
            {item_no: 4, src: 'simple/item4.jpg', title:'셀러리그래놀라치즈샐러드',sub_title:'샌드위치 속재료로 딱',level:'쉬움',time:'15분',coment:'크림치즈의 묵직한 맛이 셀러리의 산뜻한 맛과 밸런스를 잘 잡아주는 샐러드입니다. 어슷하게 잘게 썬 셀러리와 오이의 씹히는 맛이 좋아 빵 사이에 넣어 샌드위치 재료로활용해도 좋답니다. 그래놀라를 넣어 통곡물의 영양을 더하고 식감도 더욱 살려봤어요!',
                ingredient:[
                    {name:'셀러리',count:'1대',cost:'3900원'},
                    {name:'오이',count:'1개',cost:'2900원'},
                    {name:'그래놀라',count:'4큰술',cost:'1900원'},
                    {name:'크림치즈',count:'2큰술',cost:'3900원'},
                    {name:'사과식초',count:'1큰술',cost:'2900원'},
                    {name:'설탕',count:'½큰술',cost:'1900원'},
                    {name:'소금, 후추가루',count:'약간씩',cost:'3900원'},
                ] 
            },
            {item_no: 5, src: 'simple/item5.jpg', title:'에그 크로와상 샌드위치',sub_title:'uz_ee_na님의',level:'쉬움',time:'20분',coment:'집에서 에어프라이어로 크루아상 샌드위치를 만들 수 있다는 사실! 알고 계셨나요? 크루아상 생지를 이용하면 쉽고 간단한 레시피예요. 크루아상 속에 햄, 루꼴라, 스크램블 에그 등을 넣어 에그 크루아상 샌드위치를 만들었답니다. 만들기 쉬워 아이들 간식으로도 OK! 주말 홈 브런치로도 제격인 에그 크루아상 샌드위치! 꼭 한 번 만들어 보세요~',
                ingredient:[
                    {name:'크루아상 생지 (또는 크루아상)',count:'2개',cost:'3900원'},
                    {name:'슬라이스 햄',count:'4장',cost:'2900원'},
                    {name:'루꼴라',count:'한 줌',cost:'1900원'},
                    {name:'아보카도',count:'½개',cost:'3900원'},
                    {name:'파메르산 치즈 가루',count:'약간',cost:'2900원'},
                    {name:'파슬리 가루',count:'약간',cost:'1900원'},
                    {name:'달걀',count:'3개',cost:'3900원'},
                    {name:'마요네즈',count:'1큰술',cost:'1900원'},
                    {name:'디종 머스터드',count:'3큰술',cost:'3900원'},
                    {name:'레몬즙',count:'1작은술',cost:'2900원'},
                    {name:'카레 가루',count:'½큰술',cost:'1900원'},
                ] 
            },
            {item_no: 6, src: 'simple/item6.jpg', title:'뿌리채소볶음',sub_title:'건강한 식탁을 위한            ',level:'보통',time:'20분',coment:'추운 겨울을 이겨내고 땅 속 기운을 그대로 담은 뿌리채소는 겨울철 보약이랍니다. 비타민 C와 식이섬유가 풍부한 연근은 기미, 여드름 개선에 도움을 주고 신경을 안정시켜 불면증을 완화해준답니다. 또한 우엉은 신장 기능을 향상시켜 이뇨 작용을 돕고 변비 예방과 다이어트에 효과적이지요. 연근이나 우엉 같은 뿌리채소는 주로 짭조름하게 양념해 조림으로 만들지만 간을 약하게 하고 살짝 볶으면 아삭아삭 씹는 맛이 좋고 더 건강하게 즐길 수 있답니다.',
                ingredient:[
                    {name:'연근',count:'1개',cost:'3900원'},
                    {name:'우엉',count:'1대',cost:'2900원'},
                    {name:'당근',count:'1/2개',cost:'1900원'},
                    {name:'홍고추',count:'1개',cost:'3900원'},
                    {name:'식초',count:'1큰술',cost:'2900원'},
                    {name:'참기름',count:'1큰술',cost:'1900원'},
                    {name:'통깨',count:'약간',cost:'3900원'},
                    {name:'식용유',count:'약간',cost:'1900원'},
                    {name:'맛술',count:'3큰술',cost:'3900원'},
                    {name:'레몬즙',count:'1작은술',cost:'2900원'},
                    {name:'카레 가루',count:'½큰술',cost:'1900원'},
                ] 
            },
            {item_no: 7, src: 'simple/item7.jpg', title:'우동',sub_title:'오동통한 면과 시원한 국물',level:'보통',time:'20분',coment:'오동통한 면과 시원한 국물 맛이 조화로운 우동! 대단히 특별한 재료가 들어 있지 않아도 속을 든든하게 채워주는 맛이죠. 이러한 이유 때문에 많은 사람들이 휴게소에서 우동을 찾게 되는 거 아닐까요? 최소한의 재료로 마음까지 따뜻하게 데워줄 우동 한 그릇. 오늘의 메뉴로 선정해 보는 건 어떨까요?',
                ingredient:[
                    {name:'냉동 우동면',count:'2개',cost:'3900원'},
                    {name:'쑥갓',count:'약간',cost:'2900원'},
                    {name:'쪽파',count:'3~4대',cost:'1900원'},
                    {name:'마른 김',count:'1/2장',cost:'3900원'},
                    {name:'물',count:'1L',cost:'2900원'},
                    {name:'국시장국(또는 쯔유)',count:'8큰술',cost:'1900원'},
                ] 
            },
            {item_no: 8, src: 'simple/item8.jpg', title:'미나리 조개탕',sub_title:'What is MINARI?',level:'쉬움',time:'20분',coment:'간단한 재료로 시원한 국물과 향긋함을 한 번에 즐길 수 있는 레시피를 소개해 드릴게요. 조개탕은 원래 시원하지만, 미나리를 넣으면 훨씬 더 개운하고 향긋한 맛을 낼 수 있답니다. 조개는 많이 끓이면 살이 줄어들 수 있으니 오래 끓이지 않고 드셔보세요!',
                ingredient:[
                    {name:'미나리',count:'100g',cost:'3900원'},
                    {name:'모시조개',count:'1kg',cost:'2900원'},
                    {name:'홍고추',count:'1개',cost:'1900원'},
                    {name:'청양고추',count:'1개',cost:'3900원'},
                    {name:'다시마 (4*4cm)',count:'1장',cost:'2900원'},
                    {name:'물',count:'8컵',cost:'1900원'},
                ]
            },
        ],
        // 한식
        [
            {item_no: 1, src: 'kfood/item1.jpg', title:'황태갈비',sub_title:'근사한 밥도둑',level:'쉬움',time:'25분',coment:'바닷바람에 얼고 녹기를 수없이 반복하며 더 부드럽고 쫄깃해지는 황태. 갈비 양념을 황태에 입혀 구워내면 색다르면서도 근사한 밥도둑이 된답니다. 달짝지근한 양념과 짭조름하면서도 담백한 황태살이 굉장히 잘 어울려요. 밥 한 공기 뚝딱은 시간 문제랍니다~',
                ingredient:[
                    {name:'황태',count:'1마리',cost:'3900원'},
                    {name:'밀가루',count:'4큰술',cost:'2900원'},
                    {name:'전분',count:'2큰술',cost:'1900원'},
                    {name:'식용유',count:'약간',cost:'3900원'},
                    {name:'간장',count:'2큰술',cost:'2900원'},
                    {name:'올리고당',count:'1큰술',cost:'1900원'},
                    {name:'갈색 설탕',count:'1큰술',cost:'3900원'},
                    {name:'맛술',count:'2큰술',cost:'2900원'},
                    {name:'다진 마늘',count:'2큰술',cost:'1900원'},
                    {name:'다진 파',count:'2큰술',cost:'3900원'},
                    {name:'참기름',count:'1큰술',cost:'2900원'},
                    {name:'통깨',count:'약간',cost:'1900원'},
                ]
            },
            {item_no: 2, src: 'kfood/item2.jpg', title:'굴순두부찌개',sub_title:'부드럽고 칼칼한 국물맛',level:'쉬움',time:'45분',coment:'굴은 바다의 우유라고 부를 정도로 영양가가 풍부합니다. 다양한 요리로 활용할 수 있지만 기본적으로 세척을 잘해야 탈이 나지 않아요. 이번엔 부드러우면서도 칼칼한 순두부찌개에 넣어 끓여봤어요. 굴순두부찌개를 끓일 때는 굴을 마지막에 넣어야 향을 제대로 즐길 수 있답니다.',
                ingredient:[
                    {name:'굴',count:'130g',cost:'3900원'},
                    {name:'순두부',count:'350g',cost:'2900원'},
                    {name:'달걀',count:'1개',cost:'1900원'},
                    {name:'애호박',count:'120g',cost:'3900원'},
                    {name:'양파',count:'50g',cost:'2900원'},
                    {name:'대파',count:'20g',cost:'1900원'},
                    {name:'청양고추',count:'1개',cost:'3900원'},
                    {name:'홍고추',count:'1개',cost:'2900원'},
                    {name:'고춧가루',count:'2큰술',cost:'1900원'},
                    {name:'식용유',count:'3큰술',cost:'3900원'},
                    {name:'국간장',count:'2큰술',cost:'2900원'},
                    {name:'다진 마늘',count:'1큰술',cost:'1900원'},
                    {name:'설탕',count:'½큰술',cost:'3900원'},
                    {name:'소금',count:'½큰술',cost:'2900원'},
                    {name:'후추',count:'1작은술',cost:'1900원'},
                ]
            },
            {item_no: 3, src: 'kfood/item3.jpg', title:'대패삼겹살고추장찌개',sub_title:'진하고 칼칼한 국물맛',level:'쉬움',time:'40분',coment:'국물 요리에 대패삼겹살을 넣으면 국물 맛이 진해지지만 너무 많이 넣으면 단맛이 강할 수 있어요. 그래서 대패삼겹살은 매콤한 고추장을 넣은 고추장찌개와 찰떡궁합이랍니다. 여기에 느타리버섯을 넣으면 감칠맛까지 더해져 더욱 맛이 좋겠죠?',
                ingredient:[
                    {name:'대패삼겹살',count:'200g',cost:'3900원'},
                    {name:'감자',count:'250g',cost:'2900원'},
                    {name:'양파',count:'80g',cost:'1900원'},
                    {name:'느타리버섯',count:'65g',cost:'3900원'},
                    {name:'대파',count:'20g',cost:'2900원'},
                    {name:'청양고추',count:'1개',cost:'1900원'},
                    {name:'홍고추',count:'1개',cost:'2900원'},
                    {name:'물',count:'100ml',cost:'1900원'},
                    {name:'고춧가루',count:'1큰술',cost:'3900원'},
                    {name:'설탕',count:'1큰술',cost:'2900원'},
                    {name:'국간장',count:'3큰술',cost:'1900원'},
                    {name:'고추장',count:'1큰술',cost:'3900원'},
                    {name:'다진 마늘',count:'1큰술',cost:'2900원'},
                    {name:'참기름',count:'1큰술',cost:'1900원'},
                    {name:'식용유',count:'2큰술',cost:'1900원'},
                ]
            },
            {item_no: 4, src: 'kfood/item4.jpg', title:'[강레오] 고등어구이',sub_title:'냄새 없이 겉바속촉',level:'쉬움',time:'20분',coment:'냄새 때문에 집에서 쉽게 도전하기 힘들었던 고등어 구이! but 강레오 셰프의 고등어구이 레시피만 있다면 이젠 집에서도 문제 없답니다. 냄새 하나 없이 겉은 바삭, 속은 촉촉한 고등어구이 요리해 보세요~!',
                ingredient:[
                    {name:'고등어 필렛',count:'130g',cost:'3900원'},
                    {name:'오일',count:'적당량',cost:'2900원'},
                    {name:'소금',count:'적당량',cost:'1900원'},
                    {name:'후춧가루',count:'적당량',cost:'3900원'},
                ]
            },
            {item_no: 5, src: 'kfood/item5.jpg', title:'채식구절판',sub_title:'정성 가득 정갈한 차림상',level:'보통',time:'40분',coment:'다가오는 명절을 맞아 손님 맞이용으로 제격인 정갈한 채식 메뉴 소개해드릴게요. 바로 우리나라 전통 음식 구절판인데요. 구절판은 갖가지 채소를 밀전병에 싸먹는 고급 한식 요리예요. 여기에 고기나 해산물 없이 오직 채소로만 재료를 준비했답니다. 기름진 음식과 육류 섭취가 잦은 명절 메뉴들 사이에서 채식구절판으로 음식의 밸런스를 맞춰주세요. 밀전병에 채소를 올려 겨자소스에 콕 찍어먹으면 고급 한정식집 부럽지 않은 맛을 집에서도 즐기실 수 있답니다. 그럼 정성 가득한 채식구절판 레시피, 바로 보실까요?',
                ingredient:[
                    {name:'표고',count:'2개',cost:'3900원'},
                    {name:'오이',count:'1/2개',cost:'2900원'},
                    {name:'당근',count:'1/2개',cost:'1900원'},
                    {name:'숙주',count:'한 줌',cost:'3900원'},
                    {name:'애호박',count:'1/4개',cost:'2900원'},
                    {name:'우엉',count:'1토막',cost:'1900원'},
                    {name:'목이버섯',count:'약간',cost:'2900원'},
                    {name:'밀가루',count:'1컵',cost:'1900원'},
                    {name:'간장',count:'1큰술',cost:'3900원'},
                    {name:'맛술',count:'1큰술',cost:'2900원'},
                    {name:'설탕',count:'2/1큰술',cost:'1900원'},
                    {name:'다진 마늘',count:'1작은술',cost:'3900원'},
                    {name:'참기름',count:'1큰술',cost:'2900원'},
                    {name:'후춧가루',count:'약간',cost:'1900원'},
                    {name:'연겨자',count:'1/2큰술',cost:'1900원'},
                ]
            },
            {item_no: 6, src: 'kfood/item6.jpg', title:'김치말이두부찜',sub_title:'Vege is',level:'쉬움',time:'30분',coment:'김치와 두부의 조합을 가장 맛있게 즐기는 방법. 노릇하게 지진 고소한 두부와 감칠맛 더해진 매콤한 김치가 만났어요. 다른 반찬 필요 없이 자작하게 끓인 김치말이두부찜 한 접시면 밥 두 공기는 금세 뚝딱! 만드는 정성만큼 맛도 보장할 수 있는 요리로 오늘의 한끼를 완성해보세요.',
                ingredient:[
                    {name:'신김치',count:'½포기',cost:'3900원'},
                    {name:'두부',count:'1모',cost:'2900원'},
                    {name:'느타리 한줌',count:'100g',cost:'1900원'},
                    {name:'양파',count:'½개',cost:'3900원'},
                    {name:'대파',count:'½대',cost:'2900원'},
                    {name:'채수',count:'2+½컵',cost:'1900원'},
                    {name:'들기름',count:'2큰술',cost:'2900원'},
                    {name:'간장(국간장)',count:'1큰술',cost:'1900원'},
                    {name:'된장',count:'½큰술',cost:'3900원'},
                    {name:'고춧가루',count:'1큰술',cost:'2900원'},
                    {name:'김치국물',count:'⅓컵',cost:'1900원'},
                    {name:'다진 마늘',count:'1큰술',cost:'3900원'},
                    {name:'설탕',count:'1작은술',cost:'2900원'},
                    {name:'후춧가루',count:'약간',cost:'1900원'},
                ]
            },
            {item_no: 7, src: 'kfood/item7.jpg', title:'김치 비빔 국수',sub_title:'매콤새콤 입맛 돋우는',level:'쉬움',time:'25분',coment:'식감 좋은 중면에 매콤 새콤 쫑쫑 썬 김치를 넣은 빨간 양념장을 잘 버무린 뒤 상큼한 오이 고명을 듬뿍~ 안 먹어봐도 맛이 짐작 가는 확실한 비주얼의 김치비빔국수예요. 아삭아삭 씹히는 김치와 싱싱하고 청량한 오이, 무엇보다 비빔 양념장의 황금 레시피가 더해져 간단하지만 완벽한 한 그릇을 선사할 거랍니다.',
                ingredient:[
                    {name:'신김치',count:'2컵',cost:'3900원'},
                    {name:'중면',count:'200g',cost:'2900원'},
                    {name:'오이',count:'1/2개',cost:'1900원'},
                    {name:'깨',count:'약간',cost:'3900원'},
                    {name:'고추장',count:'2큰술',cost:'2900원'},
                    {name:'식초',count:'2큰술',cost:'1900원'},
                    {name:'올리고당',count:'1큰술',cost:'2900원'},
                    {name:'간장',count:'1큰술',cost:'1900원'},
                    {name:'설탕',count:'1큰술',cost:'3900원'},
                    {name:'맛술',count:'1큰술',cost:'2900원'},
                    {name:'참기름',count:'1큰술',cost:'1900원'},
                    {name:'후춧가루',count:'약간',cost:'1900원'},
                ]
            },
            {item_no: 8, src: 'kfood/item8.jpg', title:'미나리 전',sub_title:'What is MINARI?',level:'쉬움',time:'30분',coment:'봄 향기를 머금은 미나리는 단백질, 철분, 칼슘, 인 등의 다양한 무기질과 섬유질이 풍부하여 혈액을 정화하는데 도움을 준다고 해요. 그~래서 준비한 메뉴! 봄 향기 머금은 향긋한 미나리를 맛있게 즐길 수 있는 ‘미나리 전’이랍니다. 미나리만 있으면 간단하게 만들 수 있어 입맛이 없을 때, 빠르게 부쳐 식탁에 내어보세요. 기름에 부치는 소리가 늘 좋은 전! 막걸리와 곁들여 드셔보시면 어떨까요?',
                ingredient:[
                    {name:'미나리',count:'200g',cost:'3900원'},
                    {name:'식용유',count:'적당량',cost:'2900원'},
                    {name:'부침가루',count:'1컵',cost:'1900원'},
                    {name:'전분',count:'2큰술',cost:'3900원'},
                    {name:'물',count:'1컵',cost:'2900원'},
                    {name:'간장',count:'1큰술',cost:'1900원'},
                    {name:'맛술',count:'½큰술',cost:'2900원'},
                    {name:'식초',count:'1작은술',cost:'1900원'},
                    {name:'잘게 썬 양파',count:'약간',cost:'3900원'},
                    {name:'홍고추',count:'약간',cost:'2900원'},
                    {name:'통깨',count:'약간',cost:'1900원'},
                ]
            },
        ],
        // 양식
        [
            {item_no: 1, src: 'wfood/item1.jpg', title:'구운 브리 치즈 샐러드',sub_title:'한 점의 예술 작품같은',level:'쉬움',time:'20분',coment:'피트 몬드리안이란 작가의 그림에서 영감을 받아 만든 샐러드예요. 치즈는 녹아내릴 수 있어서 재빠르게 굽는 것이 중요하답니다. 브리 치즈 대신 까망베르 치즈를 사용해도 좋아요!',
                ingredient:[
                    {name:'브리치즈',count:'½개',cost:'3900원'},
                    {name:'어린 양배추',count:'1개',cost:'2900원'},
                    {name:'애호박',count:'⅓개',cost:'1900원'},
                    {name:'비트',count:'30g',cost:'2900원'},
                    {name:'파프리카 (빨강)',count:'½개',cost:'3900원'},
                    {name:'파프리카 (노란색)',count:'½개',cost:'4900원'},
                    {name:'아스파라거스',count:'1줄기',cost:'6900원'},
                    {name:'프리세',count:'2줄기',cost:'5900원'},
                    {name:'소렐',count:'3장',cost:'4900원'}
                ]
            },
            {item_no: 2, src: 'wfood/item2.jpg', title:'선 드라이 토마토 부르스게타',sub_title:'선 드라이 토마토 페스토로 만든',level:'쉬움',time:'25분',coment:'선 드라이 토마토 페스토를 활용해 만든 초간단 부르스게타! 부르스게타는 바게트에 치즈, 과일, 소스 등을 얹은 이탈리아 요리를 말해요. 오늘은 선 드라이 토마토 페스토로 더 쉽고 더 풍미 있는 부르스게타를 만들어 볼 건데요. 바게트, 선 드라이 페스토, 올리브오일, 치즈만 있으면 요리가 완성된답니다. 식전에 입맛을 돋우는 전채요리 혹은 와인 안주 등으로 다양하게 활용해 보세요!',
                ingredient:[
                    {name:'바게트',count:'½개',cost:'3900원'},
                    {name:'선 드라이 토마토 페스토',count:'2큰술',cost:'2900원'},
                    {name:'올리브오일',count:'약간',cost:'1900원'},
                    {name:'파마산 치즈',count:'약간',cost:'2900원'},
                    {name:'파슬리',count:'약간',cost:'3900원'}
                ]
            },
            {item_no: 3, src: 'wfood/item3.jpg', title:'광어 구이 아쿠아빠짜',sub_title:'바지락 스프의 깊은 맛',level:'보통',time:'30분',coment:'‘아쿠아빠짜’는 이탈리아어로 ‘미친 물’이라는 뜻이예요. 다소 과격한 표현이지만 그만큼 맛있다는 의미죠. 만약 생선 굽기가 귀찮다면 구이를 빼고 바지락만 스프만으로도 훌륭한 요리가 된답니다.',  
                ingredient:[
                    {name:'광어',count:'¼마리',cost:'3900원'},
                    {name:'바지락',count:'20개',cost:'2900원'},
                    {name:'아스파라거스',count:'2줄기',cost:'1900원'},
                    {name:'방울토마토',count:'5개',cost:'2900원'},
                    {name:'마늘',count:'5개',cost:'3900원'},
                    {name:'화이트 와인',count:'100ml',cost:'4900원'},
                    {name:'타임',count:'5줄기',cost:'6900원'},
                    {name:'버터',count:'1티스푼',cost:'5900원'},
                    {name:'엑스트라 버진',count:'2티스푼',cost:'4900원'},
                    {name:'이태리 파슬리',count:'5줄기',cost:'3900원'},
                    {name:'케이퍼',count:'10알',cost:'2900원'},
                    {name:'적양파',count:'20g',cost:'1900원'},
                    {name:'레몬',count:'¼개',cost:'2900원'},
                    {name:'처빌',count:'5장',cost:'3900원'}
                ]
            },
            {item_no: 4, src: 'wfood/item4.jpg', title:'나폴리풍 해산물 리소토',sub_title:'바다의 맛과 향이 물씬',level:'보통',time:'30분',coment:'갖가지 해물을 가득 넣고 조개 스톡과 함께 끓여낸 나폴리풍의 리소토예요~ 토마토소스를 더해 또 다른 맛의 리소토로 만들수도 있답니다!',
                ingredient:[
                    {name:'쌀',count:'80g',cost:'3900원'},
                    {name:'바질',count:'1장',cost:'2900원'},
                    {name:'양파',count:'70g',cost:'1900원'},
                    {name:'그라나 파다노 치즈',count:'4티스푼',cost:'2900원'},
                    {name:'버터',count:'2티스푼',cost:'3900원'},
                    {name:'마늘',count:'6개',cost:'4900원'},
                    {name:'방울토마토',count:'5개',cost:'6900원'},
                    {name:'오징어',count:'⅓마리',cost:'5900원'},
                    {name:'관자',count:'2마리',cost:'4900원'},
                    {name:'새우',count:'5마리',cost:'1900원'},
                    {name:'홍합',count:'5개',cost:'2900원'},
                    {name:'화이트 와인',count:'100ml',cost:'3900원'},
                    {name:'바지락',count:'10개',cost:'4900원'},
                    {name:'소금, 후추',count:'약간',cost:'6900원'},
                    {name:'올리브유',count:'약간',cost:'5900원'},

                ]
            },
            {item_no: 5, src: 'wfood/item5.jpg', title:'올리브 레몬 광어 구이',sub_title:'',level:'보통',time:'30분',coment:'담백한 광어구이에 고소한 올리브 페스토, 상큼한 레몬 마늘 소스의 조화가 인상적인 요리예요. 레몬 마늘 소스는 너무 오래 끓이면 레몬의 텁텁한 맛까지 느껴지므로 농도가 나올 때까지만 살짝 끓여주세요.',
                ingredient:[
                    {name:'브리치즈',count:'½개',cost:'3900원'},
                    {name:'어린 양배추',count:'1개',cost:'2900원'},
                    {name:'애호박',count:'⅓개',cost:'1900원'},
                    {name:'비트',count:'30g',cost:'2900원'},
                    {name:'파프리카 (빨강)',count:'½개',cost:'3900원'},
                    {name:'파프리카 (노란색)',count:'½개',cost:'4900원'},
                    {name:'아스파라거스',count:'1줄기',cost:'6900원'},
                    {name:'프리세',count:'2줄기',cost:'5900원'},
                    {name:'소렐',count:'3장',cost:'4900원'}
                ]
            },
            {item_no: 6, src: 'wfood/item6.jpg', title:'밀라노풍 까르보나라',sub_title:'상큼 고소 담백의 조화',level:'쉬움',time:'30분',coment:'실제 이탈리아에는 크림이 들어간 파스타 요리가 거의 없다고 해요. 정통 이태리식 까르보나라는 달걀을 넣어 만든 요리로, 우리나라에서 크림으로 변한 것이라고 하죠. 노른자로 고소한 맛을 살리고 베이컨을 올린 밀라노식 까르보나라 함께 만들어 볼까요?',
                ingredient:[
                    {name:'초록 올리브',count:'20개',cost:'3900원'},
                    {name:'레몬',count:'½개',cost:'2900원'},
                    {name:'마늘',count:'2개',cost:'1900원'},
                    {name:'채소 스톡',count:'100ml',cost:'2900원'},
                    {name:'버터',count:'2티스푼',cost:'3900원'},
                    {name:'광어',count:'½마리',cost:'4900원'},
                    {name:'양파',count:'⅓개',cost:'6900원'},
                    {name:'꿀',count:'¼티스푼',cost:'5900원'},
                    {name:'쏘렐',count:'5장',cost:'4900원'},
                    {name:'타임',count:'5줄기',cost:'4900원'},
                    {name:'발사믹 리덕션',count:'약간',cost:'6900원'},
                    {name:'소금, 후추',count:'약간',cost:'5900원'},
                    {name:'올리브유',count:'약간',cost:'4900원'}
                ]
            },
            {item_no: 7, src: 'wfood/item7.jpg', title:'샤프론 리소토',sub_title:'귀한 향신료의 향미',level:'보통',time:'35분',coment:'값비싸고 귀한 향신료 샤프론, 이제는 등급에 따라 구하기 더욱 쉬워져 요리에 자주 쓰이죠~ 샤프론의 향과 그라나 파다노 치즈의 풍미가 물씬 나는 리소토 함께 만들어 보아요~',
                ingredient:[
                    {name:'쌀',count:'80g',cost:'3900원'},
                    {name:'양파',count:'70g',cost:'2900원'},
                    {name:'마늘',count:'1개',cost:'1900원'},
                    {name:'그라나 파다노 치즈',count:'4티스푼',cost:'2900원'},
                    {name:'버터',count:'2티스푼',cost:'3900원'},
                    {name:'방울토마토',count:'5개',cost:'4900원'},
                    {name:'관자',count:'2마리',cost:'6900원'},
                    {name:'새우',count:'6마리',cost:'5900원'},
                    {name:'초록콩',count:'20알',cost:'4900원'},
                    {name:'샤프론',count:'1티스푼',cost:'4900원'},
                    {name:'화이트 와인',count:'100ml',cost:'6900원'},
                    {name:'조개 스톡',count:'200ml',cost:'5900원'},
                    {name:'소금, 후추',count:'약간',cost:'4900원'},
                    {name:'올리브유',count:'약간',cost:'5900원'},
                ]
            },
            {item_no: 8, src: 'wfood/item8.jpg', title:'토마토 팍시',sub_title:'맛있는 프랑스 가정식',level:'쉬움',time:'40분',coment:'보기에도 예쁘고 따듯한 맛이 느껴지는 토마토 팍시(Tomates farcie) 팍시는 프랑스어로 ‘다진 고기나 채소로 속을 채운’ 이란 뜻이에요. 토마토 팍시는 토마토 속을 파내어 쇠고기와 양파 등을 볶아 채워 넣고, 치즈를 올려 오븐에 구워 만드는 프랑스 가정식이랍니다. 에피타이저로도 좋고 맛있는 다이어트로 즐길 수 있는 토마토 팍시, 꼭 한 번 만들어 보세요.',
                ingredient:[
                    {name:'토마토',count:'4개',cost:'3900원'},
                    {name:'양파',count:'¼개',cost:'2900원'},
                    {name:'다진 마늘',count:'½큰술',cost:'1900원'},
                    {name:'소금',count:'약간',cost:'2900원'},
                    {name:'후춧가루',count:'약간',cost:'3900원'},
                    {name:'다진 쇠고기',count:'200g',cost:'4900원'},
                    {name:'빵가루',count:'⅓컵',cost:'6900원'},
                    {name:'파마산 치즈 가루',count:'2큰술',cost:'5900원'},
                    {name:'모차렐라 피자 치즈',count:'1컵',cost:'4900원'},
                    {name:'다진 파슬리 (생략 가능)',count:'약간',cost:'4900원'},
                    {name:'올리브오일',count:'약간',cost:'6900원'},
                    {name:'소금',count:'약간',cost:'4900원'},
                    {name:'후춧가루',count:'약간',cost:'5900원'},
                ]
            },
        ],
        // 일식
        [
            {item_no: 1, src: 'jfood/item1.jpg', title:'튀김덮밥(텐동)',sub_title:'보기만해도 행복해지는',level:'보통',time:'45분',coment:'어떤 튀김부터 먹을까 행복한 고민이 돼요~ 하나씩 골라먹는 재미가 있는 튀김덮밥을 준비했답니다. 재료에는 없지만 평소 좋아했던 재료들을 튀겨내도 좋겠죠? 정성을 더한 가쓰오부시 소스도 꼭 곁들여주세요!',
                ingredient:[
                    {name:'생새우',count:'6마리',cost:'3900원'},
                    {name:'단호박',count:'1/6개',cost:'2900원'},
                    {name:'연근',count:'1/6개',cost:'1900원'},
                    {name:'깻잎',count:'2장',cost:'2900원'},
                    {name:'표고버섯',count:'2개',cost:'3900원'},
                    {name:'꽈리고추',count:'4개',cost:'4900원'},
                    {name:'김',count:'2장',cost:'6900원'},
                    {name:'밥',count:'2공기',cost:'5900원'},
                    {name:'튀김가루',count:'2컵',cost:'4900원'},
                    {name:'탄산수',count:'1/2컵',cost:'4900원'},
                    {name:'달걀',count:'1개',cost:'6900원'},
                    {name:'미림',count:'2큰술',cost:'4900원'},
                    {name:'간장',count:'4큰술',cost:'5900원'},
                    {name:'설탕',count:'2큰술',cost:'6900원'},
                    {name:'다시마(4*4cm)',count:'1장',cost:'4900원'},
                    {name:'가쓰오부시',count:'한줌',cost:'5900원'},
                ]
            },
            {item_no: 2, src: 'jfood/item2.jpg', title:'유자 삼치조림',sub_title:'색다른 조림요리',level:'보통',time:'40분',coment:'통통하게 살이 오른 제철 삼치에 유자 향이 더해진 소스를 넣어 짭조름하게 조려냈어요. 상큼한 유자 향이 삼치와 잘 어울리는 색다른 조림요리예요. 정갈하고 고급스럽게 식탁에 올려보세요!',
                ingredient:[
                    {name:'삼치',count:'1마리',cost:'3900원'},
                    {name:'마늘',count:'5쪽',cost:'2900원'},
                    {name:'페페론치노 (또는 건고추)',count:'6개 (1개)',cost:'1900원'},
                    {name:'유자청',count:'1큰술',cost:'2900원'},
                    {name:'녹말가루',count:'⅓컵',cost:'3900원'},
                    {name:'맛술',count:'1큰술',cost:'4900원'},
                    {name:'후춧가루',count:'약간',cost:'6900원'},
                    {name:'식용유',count:'적당량',cost:'5900원'},
                    {name:'간장',count:'2큰술',cost:'4900원'},
                    {name:'맛술',count:'2큰술',cost:'4900원'},
                    {name:'물엿',count:'2큰술',cost:'6900원'},
                    {name:'설탕',count:'½큰술',cost:'4900원'},
                    {name:'생강가루',count:'약간',cost:'5900원'},
                    {name:'후춧가루',count:'약간',cost:'6900원'},
                ]
            },
            {item_no: 3, src: 'jfood/item3.jpg', title:'어묵 전골',sub_title:'호호~불어가며 먹는',level:'보통',time:'25분',coment:'가끔은 추운 날 포장마차에서 호호 불어가며 먹던 어묵이 생각나더라고요. 집에서 더욱 풍성한 양과 맛으로 어묵 전골을 즐겨보세요! 어묵, 채소, 국물 등 다양한 재료가 한 냄비 안에서 보글보글 끓는 모습! 상상되지 않으시나요? 따끈한 국물과 어묵 한 입! 겨울철 별미랍니다.',
                ingredient:[
                    {name:'모듬어묵',count:'500g',cost:'3900원'},
                    {name:'곤약',count:'50g',cost:'2900원'},
                    {name:'대파',count:'1/2대',cost:'1900원'},
                    {name:'마늘',count:'1톨',cost:'2900원'},
                    {name:'무',count:'1/6개',cost:'3900원'},
                    {name:'건고추',count:'1개',cost:'4900원'},
                    {name:'연겨자',count:'약간',cost:'6900원'},
                    {name:'삶은 달걀',count:'2개',cost:'5900원'},
                    {name:'멸치',count:'10개',cost:'4900원'},
                    {name:'다시마',count:'1장',cost:'4900원'},
                    {name:'국간장',count:'1큰술',cost:'6900원'},
                    {name:'맛술',count:'1큰술',cost:'4900원'},
                ]
            },
            {item_no: 4, src: 'jfood/item4.jpg', title:'차슈덮밥',sub_title:'달콤 짭쪼름한 소스가 일품',level:'쉬움',time:'40분',coment:'간편하면서 근사하게 즐길 수 있는 한 그릇 덮밥 요리를 준비했어요. 차슈는 일본에서 돼지고기를 간장 소스에 부드럽게 익혀 주로 덮밥이나 라면에 곁들여 먹는데요. 양념이 깊게 밴 차슈는 감칠맛이 풍부하고 야들야들한 식감이 일품이랍니다. 자극적이지 않으면서 깊은 풍미를 느낄 수 있는 차슈덮밥을 준비해보세요.',
                ingredient:[
                    {name:'삼겹살',count:'300g',cost:'2900원'},
                    {name:'통깨',count:'약간',cost:'1900원'},
                    {name:'청주',count:'1큰술',cost:'3900원'},
                    {name:'양파',count:'1/2개',cost:'4900원'},
                    {name:'대파',count:'10cm',cost:'6900원'},
                    {name:'마늘',count:'5쪽',cost:'5900원'},
                    {name:'생강가루',count:'1/2큰술',cost:'4900원'},
                    {name:'후춧가루',count:'약간',cost:'4900원'},
                    {name:'가쓰오부시 장국',count:'1/4컵 (50ml)',cost:'6900원'},
                    {name:'맛술',count:'1/4컵',cost:'4900원'},
                    {name:'간장',count:'4큰술',cost:'4900원'},
                    {name:'올리고당',count:'2큰술',cost:'4900원'},
                    {name:'양파',count:'1/2개',cost:'6900원'},
                    {name:'깻잎',count:'4장',cost:'4900원'},
                    {name:'쪽파',count:'4줄기',cost:'4900원'},
                ]
            },
            {item_no: 5, src: 'jfood/item5.jpg', title:'타코야끼',sub_title:'겨울 간식 최강자',level:'보통',time:'20분',coment:'겨울엔, 품 안에 무조건 3천원을 들고 다녀야 합니다. 뜨끈하고 맛있는 겨울 간식이 우리를 언제 어디서 기다리고 있을 지 모를 일이니까요. 하지만 요즘처럼 길거리 음식을 먹는 것이 걱정된다면 집에서 만들어 보는 건 어떠세요? 오늘 소개해드릴 음식은 겨울철 길거리 음식 최강자 타코야끼입니다. 커다란 문어와 입천장이 뜨거워지는 반죽은 언제나 입안에서 사르르 녹아 없어지죠.',
                ingredient:[
                    {name:'문어',count:'120g',cost:'2900원'},
                    {name:'가쓰오부시',count:'한줌',cost:'1900원'},
                    {name:'쪽파',count:'반줌',cost:'3900원'},
                    {name:'파래가루',count:'1큰술',cost:'4900원'},
                    {name:'마요네즈',count:'2큰술',cost:'6900원'},
                    {name:'돈가스 소스 (또는 우스터 소스)',count:'4큰술',cost:'5900원'},
                    {name:'식용유',count:'2큰술',cost:'4900원'},
                    {name:'밀가루',count:'110g',cost:'4900원'},
                    {name:'찹쌀가루',count:'30g',cost:'6900원'},
                    {name:'베이킹 파우더',count:'1작은술',cost:'4900원'},
                    {name:'다시마육수',count:'360ml',cost:'4900원'},
                ]
            },
            {item_no: 6, src: 'jfood/item6.jpg', title:'일본식 두부튀김',sub_title:'간단하지만 폼나는',level:'쉬움',time:'20분',coment:'오늘 준비한 레시피는 "아게다시 도후"로 불리는 일본식 두부튀김인데요~ 짭조름한 소스에 두부튀김을 적셔먹는, 이자카야에서 흔히 볼 수 있는 정감있는 안주랍니다. 만드는 방법도 어렵지 않아 혼술 할 때 재빨리 만들어내기도 좋아요.',
                ingredient:[
                    {name:'두부(찌개용)',count:'1모',cost:'2900원'},
                    {name:'전분가루',count:'5큰술',cost:'1900원'},
                    {name:'실파',count:'2대',cost:'3900원'},
                    {name:'무',count:'1/8개',cost:'4900원'},
                    {name:'가쓰오부시',count:'한줌',cost:'6900원'},
                    {name:'다시마(사방 4센치)',count:'1장',cost:'5900원'},
                    {name:'간장',count:'3큰술',cost:'4900원'},
                    {name:'미림',count:'3큰술',cost:'4900원'},
                ]
            },
            {item_no: 7, src: 'jfood/item7.jpg', title:'연어오차즈케',sub_title:'녹차의 향기 싣고',level:'쉬움',time:'30분',coment:'오차즈케는 녹차에 밥을 말아먹는 일본 가정식 요리예요. 기호에 맞게 매실장아찌, 명란젓 등 다양한 고명을 얹어 먹을 수 있는데, 개인적으로 구운 연어를 얹은 담백한 연어오차즈케를 가장 좋아해요.',
                ingredient:[
                    {name:'연어',count:'50g',cost:'2900원'},
                    {name:'쪽파',count:'15g',cost:'1900원'},
                    {name:'녹차가루',count:'1큰술',cost:'3900원'},
                    {name:'뜨거운 물',count:'2½ 컵',cost:'4900원'},
                    {name:'식용유',count:'2큰술',cost:'6900원'},
                    {name:'고추냉이',count:'약간',cost:'5900원'},
                    {name:'허브솔트',count:'약간',cost:'4900원'},
                    {name:'통깨',count:'약간',cost:'4900원'},
                ]
            },
            {item_no: 8, src: 'jfood/item8.jpg', title:'치킨가라아게',sub_title:'육즙 가득한',level:'쉬움',time:'45분',coment:'치킨 가라아게는 일본 드라마나 영화에도 자주 등장해 친숙한 메뉴죠~ 오늘은 육즙이 풍부한 닭다리살을 활용해 바삭하게 튀겨 준비했어요. 자꾸만 손이 가는 양념옷을 입은 가라아게! 온 가족이 식탁에 모여 맛있게 즐길 수 있는 메뉴랍니다.',
                ingredient:[
                    {name:'닭다리살',count:'300g',cost:'2900원'},
                    {name:'양배추',count:'3잎',cost:'1900원'},
                    {name:'레몬(생략가능)',count:'1/2개',cost:'3900원'},
                    {name:'전분가루',count:'1컵',cost:'4900원'},
                    {name:'우유',count:'1/2컵',cost:'6900원'},
                    {name:'튀김기름',count:'적당량',cost:'5900원'},
                    {name:'간장',count:'1큰술',cost:'4900원'},
                    {name:'맛술',count:'1큰술',cost:'4900원'},
                    {name:'생강즙(또는 생강가루)',count:'1/2큰술(1/4작은술)',cost:'5900원'},
                    {name:'소금',count:'두꼬집',cost:'4900원'},
                    {name:'후추',count:'약간',cost:'4900원'},
                ]
            },
        ],
        // 중식
        [
            {item_no: 1, src: 'cfood/item1.jpg', title:'동파육',sub_title:'촉촉한 살코기가 먹음직스러운',level:'쉬움',time:'30분',coment:'부들부들한 살코기와 입에 착 달라붙는 듯한 양념 맛이 일품인 동파육! 맛과 향, 식감은 물론 색감까지 뛰어난 중국 요리인데요. 이름과 관련해서 훈훈한 일화가 남아 있습니다. 송나라 때 물난리가 난 마을을 "소동파"라는 시인이 백성들을 동원해 제방을 쌓음으로써 위기로부터 구한 적이 있었대요. 백성들이 고마움의 표시로 돼지고기를 보내자 "소동파"는 자신이 개발한 요리법으로 백성들과 함께 나눠 먹었는데요. 그의 마음에 감동을 받은 백성들이 그 돼지고기 요리에 동파육이라는 이름을 붙였다는 유래가 전해진답니다. 광파오븐을 사용하면 어렵게만 느껴지던 동파육도 손쉽게 만들 수 있는데요. 두툼한 삼겹살을 스팀으로 촉촉하게 익힌 후 소스에 졸여내기만 하면 뚝딱 완성된답니다!',
                ingredient:[
                    {name:'삼겹살',count:'800g',cost:'2900원'},
                    {name:'흑설탕',count:'2큰술',cost:'1900원'},
                    {name:'마늘',count:'4쪽',cost:'3900원'},
                    {name:'생강',count:'1/2쪽',cost:'4900원'},
                    {name:'대파',count:'1대',cost:'6900원'},
                    {name:'건고추',count:'2개',cost:'5900원'},
                    {name:'팔각',count:'2개',cost:'4900원'},
                    {name:'숙주',count:'한 줌',cost:'4900원'},
                    {name:'올리브오일',count:'약간',cost:'5900원'},
                    {name:'월계수잎',count:'3장',cost:'4900원'},
                    {name:'청주',count:'1/4컵',cost:'4900원'},
                    {name:'된장',count:'1큰술',cost:'4900원'},
                    {name:'굴소스',count:'1큰술',cost:'5900원'},
                    {name:'식초',count:'1큰술',cost:'4900원'},
                    {name:'간장',count:'1작은술',cost:'4900원'},
                ]
            },
            {item_no: 2, src: 'cfood/item2.jpg', title:'사천식 량반두부피',sub_title:'매콤 얼얼한 맛',level:'쉬움',time:'15분',coment:'요리에서 많이 사용하는 식재료 중 하나인 두부. 우리에겐 다소 생소하기는 하지만 두부가 익어서 엉길 때 그 겉을 긁어낸 두부피를 사용한 요리가 중국에는 많답니다. 두부피를 사천식으로 무쳐낸 요리, 함께해 보아요~',
                ingredient:[
                    {name:'오이',count:'40g',cost:'2900원'},
                    {name:'불린 목이버섯',count:'20g',cost:'1900원'},
                    {name:'홍파프리카',count:'40g',cost:'3900원'},
                    {name:'두부피',count:'200g',cost:'4900원'},
                    {name:'마늘',count:'20g',cost:'6900원'},
                    {name:'고추기름',count:'30g',cost:'5900원'},
                    {name:'마늘',count:'10알',cost:'4900원'},
                    {name:'치킨파우더',count:'30g',cost:'4900원'},
                    {name:'산초가루',count:'10g',cost:'5900원'},
                    {name:'백후추',count:'2g',cost:'4900원'},
                    {name:'설탕',count:'3g',cost:'4900원'},
                    {name:'고추씨',count:'30g',cost:'4900원'},
                ]
            },
            {item_no: 3, src: 'cfood/item3.jpg', title:'깐풍 두부 튀김 덮밥',sub_title:'광동성의 맛',level:'쉬움',time:'35분',coment:'깐풍은 ‘센불에서 마르게 볶다’라는 의미로 부드러운 두부를 바삭하게 튀겨 새콤달콤하게 먹는 중국 광동성의 가정식 요리예요~',
                ingredient:[
                    {name:'두부',count:'½모',cost:'2900원'},
                    {name:'청피망',count:'⅓개',cost:'1900원'},
                    {name:'홍피망',count:'⅓개',cost:'3900원'},
                    {name:'브로콜리',count:'3개',cost:'4900원'},
                    {name:'마늘',count:'2개',cost:'6900원'},
                    {name:'대파',count:'⅓대',cost:'5900원'},
                    {name:'사천고추',count:'3개',cost:'4900원'},
                    {name:'감자전분',count:'1컵(튀김용)',cost:'4900원'},
                    {name:'식용유',count:'3컵',cost:'5900원'},
                    {name:'청주',count:'1작은술',cost:'4900원'},
                    {name:'고추기름',count:'1과 ½큰술',cost:'4900원'},
                    {name:'후춧가루',count:'약간',cost:'4900원'},
                ]
            },
            {item_no: 4, src: 'cfood/item4.jpg', title:'어향 가지 덮밥',sub_title:'대표 중화요리',level:'쉬움',time:'35분',coment:'짜고, 달고, 시고, 매운 맛이 조화로운 어향 소스의 중독성 있는 유혹! 인기 있는 중화요리 어향가지를 덮밥 요리로 함께 만들어 보세요~',
                ingredient:[
                    {name:'다진 돼지고기',count:'50g',cost:'2900원'},
                    {name:'가지',count:'1개',cost:'1900원'},
                    {name:'샐러리',count:'⅓대',cost:'3900원'},
                    {name:'홍고추',count:'1개',cost:'4900원'},
                    {name:'청피망',count:'¼개',cost:'6900원'},
                    {name:'양파',count:'¼개',cost:'5900원'},
                    {name:'대파',count:'¼대',cost:'4900원'},
                    {name:'다진 생강',count:'약간',cost:'4900원'},
                    {name:'다진 마늘',count:'약간',cost:'5900원'},
                    {name:'감자 전분',count:'1컵',cost:'4900원'},
                    {name:'물전분',count:'1큰술',cost:'4900원'},
                    {name:'육수',count:'½컵',cost:'4900원'},
                    {name:'두반장',count:'1작은술',cost:'4900원'},
                    {name:'치킨파우더',count:'1작은술',cost:'5900원'},
                    {name:'청주',count:'1작은술',cost:'4900원'},
                    {name:'식초',count:'1큰술',cost:'4900원'},
                    {name:'간장',count:'1작은술',cost:'4900원'},
                ]
            },
            {item_no: 5, src: 'cfood/item5.jpg', title:'닭고기 마늘쫑 볶음밥',sub_title:'매콤하고 알싸한',level:'쉬움',time:'30분',coment:'마늘쫑의 알싸함과 닭고기의 쫄깃함이 어우러진 볶음밥이예요~ 순식간에 다 비워버리게 되는 마성의 맛이랍니다!',
                ingredient:[
                    {name:'다진 닭고기',count:'100g',cost:'5900원'},
                    {name:'마늘쫑',count:'5줄기(80g)',cost:'4900원'},
                    {name:'굴소스',count:'2작은술',cost:'4900원'},
                    {name:'노두유',count:'2작은술',cost:'4900원'},
                    {name:'달걀',count:'2개',cost:'2900원'},
                    {name:'대파',count:'¼대',cost:'1900원'},
                    {name:'당근',count:'⅓개(50g)',cost:'3900원'},
                    {name:'식용유',count:'3큰술',cost:'4900원'},
                    {name:'치킨파우더',count:'½작은술',cost:'6900원'},
                    {name:'소금',count:'½작은술',cost:'5900원'},
                    {name:'후춧가루',count:'약간',cost:'4900원'},
                    {name:'참기름',count:'½작은술',cost:'4900원'},
                ]
            },
            {item_no: 6, src: 'cfood/item6.jpg', title:'마라샹궈',sub_title:'스트레스 확 날려줄',level:'쉬움',time:'40분',coment:'마라샹궈는 "마라 향이 나는 냄비 음식"을 뜻하는데요. 고기와 채소, 버섯 등 각종 재료를 마라 소스와 함께 볶아 내면 손쉽게 완성할 수 있어요. 입안을 얼얼하게 만들면서도 왠지 모를 개운함이 느껴져 마니아층이 두터운 요리죠. 집에서 마라샹궈를 만들면 취향에 따라 재료를 빼거나 더하기 쉬워 더 좋답니다. 스트레스 확 날려줄 마라샹궈 만들기 도전해 보세요!',
                ingredient:[
                    {name:'마라소스',count:'30~40g',cost:'5900원'},
                    {name:'알배추',count:'4장',cost:'4900원'},
                    {name:'청경채',count:'2개(140g)',cost:'4900원'},
                    {name:'연근',count:'70g',cost:'4900원'},
                    {name:'팽이버섯',count:'50g',cost:'2900원'},
                    {name:'우삼겹',count:'100g',cost:'1900원'},
                    {name:'넓적 당면',count:'40g',cost:'3900원'},
                    {name:'다진 마늘',count:'1큰술',cost:'4900원'},
                    {name:'다진 파',count:'2큰술',cost:'6900원'},
                    {name:'식용유',count:'1큰술',cost:'5900원'},
                ]
            },
            {item_no: 7, src: 'cfood/item7.jpg', title:'게살수프',sub_title:'찬 바람 불 때 생각나는',level:'쉬움',time:'10분',coment:'따끈따끈 호로록 넘어가는 게살 수프. 찬 바람 불 때 생각나는 맛! 추운 겨울과 잘 어울리는 레시피를 준비했어요. 간단한 재료로 쉽게 중식 요리를 만들어 보세요. 집에서도 쉽게 중식 레스토랑 분위기를 낼 수 있답니다~ 게살 수프 하나면 우리 집도 중식 레스토랑!',
                ingredient:[
                    {name:'고급 맛살 또는 게살 통조림',count:'200g',cost:'5900원'},
                    {name:'팽이버섯',count:'한 줌',cost:'4900원'},
                    {name:'달걀',count:'2개',cost:'4900원'},
                    {name:'실파',count:'2줄기',cost:'4900원'},
                    {name:'전분물 (물 ½컵, 전분 2큰술)',count:'½컵',cost:'2900원'},
                    {name:'후춧가루',count:'약간',cost:'1900원'},
                    {name:'청주',count:'1큰술',cost:'3900원'},
                    {name:'참기름',count:'1큰술',cost:'4900원'},
                    {name:'치킨스톡',count:'3g',cost:'6900원'},
                ]
            },
            {item_no: 8, src: 'cfood/item8.jpg', title:'고추 듬뿍 닭튀김',sub_title:'알싸한 중국식 닭튀김',level:'보통',time:'35분',coment:'매운 고추를 듬뿍 넣어 닭고기와 함께 볶아내 맵고 알싸한 맛이 특징인 사천 지방의 닭 요리, 함께 만들어 볼까요?',
                ingredient:[
                    {name:'닭다리살',count:'4개',cost:'5900원'},
                    {name:'마늘',count:'한 줌',cost:'4900원'},
                    {name:'생강',count:'1개',cost:'4900원'},
                    {name:'사천고추',count:'20개',cost:'4900원'},
                    {name:'마른고추',count:'10개',cost:'2900원'},
                    {name:'쪽파(흰 부분)',count:'5뿌리',cost:'1900원'},
                    {name:'산초가루',count:'1작은술',cost:'3900원'},
                    {name:'간장',count:'1큰술',cost:'4900원'},
                    {name:'노두유',count:'약간',cost:'6900원'},
                    {name:'고추기름',count:'1큰술',cost:'2900원'},
                    {name:'산초기름',count:'1큰술',cost:'1900원'},
                    {name:'산초가루',count:'1작은술',cost:'3900원'},
                    {name:'치킨파우더',count:'1큰술',cost:'4900원'},
                    {name:'백후춧가루',count:'1작은술',cost:'6900원'},
                ]
            },
        ],
        // 베이킹
        [
            {item_no: 1, src: 'baking/item1.jpg', title:'아보카도 브라우니',sub_title:'달콤함에 고소한 부드러움을 더한',level:'쉬움',time:'40분',coment:'진한 초콜릿 풍미를 맛볼 수 있는 브라우니에 아보카도를 넣으면 좀 더 부드럽고 고소하게 즐길 수 있답니다. 나른한 오후, 사랑하는 사람들과 에스프레소 한 잔에 아보카도 브라우니를 나누며 티 타임을 가져보세요. 그 시간이 더욱 달콤해질 거예요!',
                ingredient:[
                    {name:'아보카도',count:'1개',cost:'5900원'},
                    {name:'시판용 브라우니 믹스',count:'320g',cost:'4900원'},
                    {name:'메이플시럽',count:'½컵',cost:'4900원'},
                    {name:'물',count:'30ml',cost:'4900원'},
                    {name:'슈가파우더',count:'½컵',cost:'2900원'},
                ]
            },
            {item_no: 2, src: 'baking/item2.jpg', title:'딸기 티라미수',sub_title:'제철 딸기로 만드는 홈 디저트',level:'보통',time:'30분',coment:'제철 딸기로 만드는 홈 디저트! 홈카페 메뉴로도 좋고, 아이들 간식으로도 좋은 딸기 티라미수예요. 달콤한 티라미수와 새콤달콤한 딸기의 조합이 최고랍니다~ 집에서 쉽게 만들어 보세요!',
                ingredient:[
                    {name:'딸기',count:'8개',cost:'5900원'},
                    {name:'카스테라',count:'1개 (100g)',cost:'4900원'},
                    {name:'마스카포네 치즈',count:'200g',cost:'4900원'},
                    {name:'민트 (생략 가능)',count:'약간',cost:'4900원'},
                    {name:'설탕',count:'40g',cost:'2900원'},
                    {name:'딸기 퓌레',count:'60g',cost:'5900원'},
                    {name:'레몬즙',count:'1작은술',cost:'4900원'},
                    {name:'생크림',count:'200g',cost:'4900원'},
                ]
            },
            {item_no: 3, src: 'baking/item3.jpg', title:'로즈 애플파이',sub_title:'바삭한 식감과 달콤한 사과팔링',level:'어려움',time:'50분',coment:'선물용으로도 안성맞춤인 로즈 애플파이! 이름 그대로 장미 모양으로 만든 애플파이입니다. 퍼프 페이스트리 반죽으로 만들어 바삭한 식감을 즐길 수 있고, 여기에 달콤한 사과필링까지 더해져 정말 맛있답니다.',
                ingredient:[
                    {name:'물',count:'410g',cost:'5900원'},
                    {name:'설탕',count:'40g',cost:'4900원'},
                    {name:'소금',count:'2g',cost:'4900원'},
                    {name:'박력분',count:'150g',cost:'4900원'},
                    {name:'무염 버터',count:'100g',cost:'2900원'},
                    {name:'사과',count:'1개',cost:'5900원'},
                    {name:'레몬',count:'½개',cost:'4900원'},
                    {name:'살구잼',count:'50g',cost:'4900원'},
                    {name:'시나몬 파우더',count:'약간',cost:'4900원'},
                ]
            },
            {item_no: 4, src: 'baking/item4.jpg', title:'레어 치즈케이크',sub_title:'오븐없이 간단하게!',level:'보통',time:'3시간20분',coment:'오븐 없이도 간단히 만들 수 있는 케이크가 있다면 믿으시겠어요? 레어 치즈케이크가 바로 그 주인공입니다. 재료도 간단하고 쉽게 만들 수 있어 초보자용 레시피로 아주 딱이죠. 입안에 넣으면 사르르 녹아 사라지는 부드러운 레어 치즈케이크를 한 번 드셔보세요.',
                ingredient:[
                    {name:'통밀 쿠키',count:'90g',cost:'5900원'},
                    {name:'무염 버터',count:'40g',cost:'4900원'},
                    {name:'크림치즈',count:'200g',cost:'4900원'},
                    {name:'설탕',count:'60g',cost:'4900원'},
                    {name:'젤라틴',count:'6g',cost:'2900원'},
                    {name:'플레인 요거트',count:'90g',cost:'5900원'},
                    {name:'생크림',count:'200g',cost:'4900원'},
                    {name:'레몬즙',count:'10g',cost:'4900원'},
                ]
            },
            {item_no: 5, src: 'baking/item5.jpg', title:'호떡 크로플 & 초코 크로플',sub_title:'방송에서 화제 되었던 크로플 레시피',level:'쉬움',time:'30분',coment:'몇 년 전 태국에 카페를 오픈했을 때 판매했던 디저트 중 하나예요. 어떤 메뉴가 좋을까 고민하면서 직원들이랑 같이 만들었던 건데, 언젠가부터 ‘크로플’이라는 이름으로 엄청난 유행이 되고 있네요. 다양한 재료로 소를 만들어 넣으면 특별하고 맛있는, 하나뿐인 크로플이 완성될 거예요.',
                ingredient:[
                    {name:'크로아상 생지(30g)',count:'4개',cost:'5900원'},
                    {name:'유기농 황설탕',count:'25g',cost:'4900원'},
                    {name:'시나몬 파우더',count:'10g',cost:'4900원'},
                    {name:'슈가 파우더',count:'1큰술',cost:'4900원'},
                    {name:'견과류 믹스',count:'15g',cost:'2900원'},
                    {name:'밀크 커버춰 초콜릿',count:'50g',cost:'5900원'},
                    {name:'다크 커버춰 초콜릿',count:'50g',cost:'4900원'},
                    {name:'초콜릿 블록',count:'30g',cost:'4900원'},
                    {name:'메이플 시럽',count:'60ml',cost:'4900원'},
                    {name:'올리브오일(혹은 기버터)',count:'약간',cost:'4900원'},
                ]
            },
            {item_no: 6, src: 'baking/item6.jpg', title:'사브레',sub_title:'우리가 좋아하는 쿠키',level:'쉬움',time:'40분',coment:'달걀을 사용하지 않고 바삭함을 최대로 올린 레시피입니다. 이번 사브레를 마스터하면 바삭바삭한 식감의 다른 종류 쿠키도 손쉽게 만들 수 있어요. 사브레 레시피에 다른 재료를 추가 배합하여 응용이 가능하거든요. 바삭하면서도 동시에 부드러운 식감을 느낄 수 있는 사브레 레 시피를 알려드릴게요!',
                ingredient:[
                    {name:'무염 버터',count:'100g',cost:'5900원'},
                    {name:'슈가파우더',count:'45g',cost:'4900원'},
                    {name:'바닐라파우더 (생략가능)',count:'2g',cost:'4900원'},
                    {name:'박력분',count:'150g',cost:'4900원'},
                ]
            },
            {item_no: 7, src: 'baking/item7.jpg', title:'키토 에그 타르트',sub_title:'고소하고 달콤한 필링',level:'보통',time:'30분',coment:'많은 사람들에게 사랑받고 있는 에그 타르트. 고소하고 달콤한 필링 그리고 바삭한 반죽이 자꾸만 먹게 되는데요. 키토 에그 타르트는 밀가루 대신 아몬드 가루, 설탕 대신 에리스리톨을 넣어 타르트 반죽을 만들어요. 반죽 위에 필링을 가득 넣어 한 입만 먹어도 행복이 가득 퍼지는 키토 에그 타르트를 만들어 보세요. 커피, 우유 어떤 음료와도 잘 어울리는 키토 에그 타르트랍니다.',
                ingredient:[
                    {name:'아몬드 가루',count:'140g',cost:'5900원'},
                    {name:'코코넛 가루',count:'40g',cost:'4900원'},
                    {name:'달걀',count:'2개',cost:'4900원'},
                    {name:'녹인 버터',count:'40g',cost:'4900원'},
                    {name:'에리스리톨',count:'15g',cost:'5900원'},
                    {name:'생크림',count:'210g',cost:'4900원'},
                    {name:'달걀노른자',count:'3개',cost:'4900원'},
                    {name:'애로루트 가루',count:'10g',cost:'4900원'},
                    {name:'바닐라 익스트랙',count:'4g',cost:'4900원'},
                ]
            },
            {item_no: 8, src: 'baking/item8.jpg', title:'비건 레몬 청포도 타르트',sub_title:'상큼함이 가득 퍼지는',level:'어려움',time:'30분',coment:'반죽을 타르트 틀에 깔고 과일, 채소 등을 채워 굽는 프랑스식 파이 타르트. 비건 레몬 청포도 타르트는 통밀가루와 버터를 섞어서 만든 반죽 대신 밀가루, 포도씨 오일을 섞어 타르트 반죽을 만들지요. 레몬 커스터드 필링을 채워 넣어 한 입만 먹어도 상큼함이 가득 퍼지는 비건 레몬 청포도 타르트를 만들어 볼게요.',
                ingredient:[
                    {name:'청포도',count:'250g',cost:'4900원'},
                    {name:'레몬 슬라이스 (두께 2~3mm)',count:'6조각',cost:'4900원'},
                    {name:'통밀가루',count:'150g',cost:'5900원'},
                    {name:'소금',count:'1g',cost:'4900원'},
                    {name:'아가베 시럽',count:'35g',cost:'4900원'},
                    {name:'포도씨 오일',count:'45g',cost:'4900원'},
                    {name:'두유',count:'200g',cost:'5900원'},
                    {name:'레몬 제스트',count:'레몬 1개 분량',cost:'4900원'},
                    {name:'칡 전분',count:'10g',cost:'4900원'},
                ]
            },
        ]
    ],
]
